//! Hand-derived prost message definitions for the OSM PBF wire format —
//! the subset Pass 1 consumes from `fileformat.proto` / `osmformat.proto`.
//!
//! Deliberately NOT generated by `prost-build`: that would put a `protoc`
//! binary and a build.rs into the aarch64-android/ios cross-compile path for
//! a wire format that has been frozen since 2011. Field numbers below are
//! copied from the canonical schemas; prost skips any tag we don't declare
//! (ways, relations, info blocks, ...), which is exactly the "decode only
//! what Pass 1 needs" posture.

/// `fileformat.proto` — envelope framing each `[BlobHeader][Blob]` pair.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlobHeader {
    /// "OSMHeader" | "OSMData" (unknown types must be skipped, per spec).
    #[prost(string, required, tag = "1")]
    pub r#type: String,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub indexdata: Option<Vec<u8>>,
    /// Byte length of the `Blob` message that follows this header.
    #[prost(int32, required, tag = "3")]
    pub datasize: i32,
}

/// `fileformat.proto` — the payload container. Only `raw` and `zlib_data`
/// are supported: zlib is the format's de-facto universal encoding (Geofabrik,
/// planet dumps); lzma/bzip2/lz4/zstd variants are rejected loudly upstream.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Blob {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub raw: Option<Vec<u8>>,
    /// Uncompressed payload size. Required by spec when compressed; used as
    /// the decompression allocation limit (RAM-budget guard).
    #[prost(int32, optional, tag = "2")]
    pub raw_size: Option<i32>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub zlib_data: Option<Vec<u8>>,
}

/// `osmformat.proto` — one decompressed OSMData payload.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PrimitiveBlock {
    /// Required by spec but unused by Pass 1 (coordinates carry no strings);
    /// optional here so a pathological-but-parseable block still yields nodes.
    #[prost(message, optional, tag = "1")]
    pub stringtable: Option<StringTable>,
    #[prost(message, repeated, tag = "2")]
    pub primitivegroup: Vec<PrimitiveGroup>,
    /// Units of 10^-9 degrees per coordinate step. Spec default: 100.
    #[prost(int32, optional, tag = "17")]
    pub granularity: Option<i32>,
    /// Offsets in 10^-9 degrees added after granularity scaling. Default 0.
    #[prost(int64, optional, tag = "19")]
    pub lat_offset: Option<i64>,
    #[prost(int64, optional, tag = "20")]
    pub lon_offset: Option<i64>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StringTable {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub s: Vec<Vec<u8>>,
}

/// Tags 3 (ways), 4 (relations), 5 (changesets) intentionally undeclared —
/// prost skips them; Pass 2 gets its own way-focused view later.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PrimitiveGroup {
    /// Plain (non-dense) nodes. Rare in real extracts but legal; dropping
    /// them silently would surface as Pass-2 lookup failures far from the
    /// actual cause.
    #[prost(message, repeated, tag = "1")]
    pub nodes: Vec<Node>,
    #[prost(message, optional, tag = "2")]
    pub dense: Option<DenseNodes>,
}

/// Plain node, coordinate fields only (keys/vals/info skipped as unknown).
/// `lat`/`lon` are absolute (NOT delta-coded), in granularity units.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Node {
    #[prost(sint64, required, tag = "1")]
    pub id: i64,
    #[prost(sint64, required, tag = "8")]
    pub lat: i64,
    #[prost(sint64, required, tag = "9")]
    pub lon: i64,
}

/// The dominant node encoding: parallel arrays where `id`, `lat`, `lon` are
/// each **delta-coded** (every element is the sint64 difference from the
/// previous one; the first is relative to 0). `keys_vals` (tag 10) and
/// `denseinfo` (tag 5) are skipped — Pass 1 wants coordinates only.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DenseNodes {
    #[prost(sint64, repeated, tag = "1")]
    pub id: Vec<i64>,
    #[prost(sint64, repeated, tag = "8")]
    pub lat: Vec<i64>,
    #[prost(sint64, repeated, tag = "9")]
    pub lon: Vec<i64>,
}

// ---------------------------------------------------------------------------
// Pass-2 views of the SAME PrimitiveBlock wire bytes.
//
// prost decodes only declared tags, so each pass gets a purpose-built view
// of one payload: Pass 1's `PrimitiveBlock` never deserializes ways, and the
// Pass-2 types below never deserialize the (large) dense-node arrays. The
// `StringTableProbe` exists so the Blueprint's semantic pre-filter can
// reject a block after decoding ONLY tag 1 — ways in a rejected block are
// wire-skipped, never materialized.
// ---------------------------------------------------------------------------

/// Minimal relevance-probe view: just the StringTable.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StringTableProbe {
    #[prost(message, optional, tag = "1")]
    pub stringtable: Option<StringTable>,
}

/// Way-bearing view of a PrimitiveBlock (granularity fields are irrelevant:
/// way refs are node IDs, not coordinates).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WayBlock {
    #[prost(message, optional, tag = "1")]
    pub stringtable: Option<StringTable>,
    #[prost(message, repeated, tag = "2")]
    pub primitivegroup: Vec<WayGroup>,
}

/// Group view declaring only ways (tag 3); nodes/dense/relations wire-skipped.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WayGroup {
    #[prost(message, repeated, tag = "3")]
    pub ways: Vec<Way>,
}

/// A way: tag-key indices into the block's StringTable plus **delta-coded**
/// node refs (same sint64 delta scheme as DenseNodes). NOTE: `id` is plain
/// int64 on the wire (not zigzag), unlike node IDs. `vals` (tag 3) and
/// `info` (tag 4) are skipped — the current filter needs key presence only.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Way {
    #[prost(int64, required, tag = "1")]
    pub id: i64,
    #[prost(uint32, repeated, tag = "2")]
    pub keys: Vec<u32>,
    #[prost(sint64, repeated, tag = "8")]
    pub refs: Vec<i64>,
}
