// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(freehikeFFI)
import freehikeFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_freehike_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_freehike_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureFreehikeFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * Where a yielded job stopped. Informational: display it, log it, but never
 * feed it back — the engine owns the durable copy.
 */
public struct CheckpointState {
    public var jobId: String
    /**
     * Processing phase the job will resume in.
     */
    public var phase: CompilePhase
    /**
     * Next block index within the phase.
     */
    public var nextBlock: UInt32
    /**
     * Byte offset into the source PBF — the real Pass 1's exact mmap
     * re-entry point (block-boundary aligned).
     */
    public var pbfByteOffset: UInt64
    /**
     * Total bytes appended to output archives so far.
     */
    public var bytesWritten: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(jobId: String, 
        /**
         * Processing phase the job will resume in.
         */phase: CompilePhase, 
        /**
         * Next block index within the phase.
         */nextBlock: UInt32, 
        /**
         * Byte offset into the source PBF — the real Pass 1's exact mmap
         * re-entry point (block-boundary aligned).
         */pbfByteOffset: UInt64, 
        /**
         * Total bytes appended to output archives so far.
         */bytesWritten: UInt64) {
        self.jobId = jobId
        self.phase = phase
        self.nextBlock = nextBlock
        self.pbfByteOffset = pbfByteOffset
        self.bytesWritten = bytesWritten
    }
}

#if compiler(>=6)
extension CheckpointState: Sendable {}
#endif


extension CheckpointState: Equatable, Hashable {
    public static func ==(lhs: CheckpointState, rhs: CheckpointState) -> Bool {
        if lhs.jobId != rhs.jobId {
            return false
        }
        if lhs.phase != rhs.phase {
            return false
        }
        if lhs.nextBlock != rhs.nextBlock {
            return false
        }
        if lhs.pbfByteOffset != rhs.pbfByteOffset {
            return false
        }
        if lhs.bytesWritten != rhs.bytesWritten {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(jobId)
        hasher.combine(phase)
        hasher.combine(nextBlock)
        hasher.combine(pbfByteOffset)
        hasher.combine(bytesWritten)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCheckpointState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CheckpointState {
        return
            try CheckpointState(
                jobId: FfiConverterString.read(from: &buf), 
                phase: FfiConverterTypeCompilePhase.read(from: &buf), 
                nextBlock: FfiConverterUInt32.read(from: &buf), 
                pbfByteOffset: FfiConverterUInt64.read(from: &buf), 
                bytesWritten: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: CheckpointState, into buf: inout [UInt8]) {
        FfiConverterString.write(value.jobId, into: &buf)
        FfiConverterTypeCompilePhase.write(value.phase, into: &buf)
        FfiConverterUInt32.write(value.nextBlock, into: &buf)
        FfiConverterUInt64.write(value.pbfByteOffset, into: &buf)
        FfiConverterUInt64.write(value.bytesWritten, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCheckpointState_lift(_ buf: RustBuffer) throws -> CheckpointState {
    return try FfiConverterTypeCheckpointState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCheckpointState_lower(_ value: CheckpointState) -> RustBuffer {
    return FfiConverterTypeCheckpointState.lower(value)
}


/**
 * Description of a compile job. Send the *same* record for every slice of
 * the same job — `job_id` + `output_dir` are the resume identity.
 */
public struct CompileJob {
    /**
     * Caller-chosen unique ID (e.g. a UUID). Checkpoints are keyed by it.
     */
    public var jobId: String
    /**
     * "west,south,east,north" in WGS84 degrees (validated on every call).
     */
    public var bbox: String
    /**
     * Minimum zoom level to generate (inclusive).
     */
    public var minZoom: UInt8
    /**
     * Maximum zoom level to generate (inclusive).
     */
    public var maxZoom: UInt8
    /**
     * Absolute path to the raw .osm.pbf extract on device storage.
     */
    public var pbfPath: String
    /**
     * Absolute path to the DEM GeoTIFF; None skips the Terrain phase.
     */
    public var demPath: String?
    /**
     * Directory owning this job's checkpoints and output archives.
     */
    public var outputDir: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Caller-chosen unique ID (e.g. a UUID). Checkpoints are keyed by it.
         */jobId: String, 
        /**
         * "west,south,east,north" in WGS84 degrees (validated on every call).
         */bbox: String, 
        /**
         * Minimum zoom level to generate (inclusive).
         */minZoom: UInt8, 
        /**
         * Maximum zoom level to generate (inclusive).
         */maxZoom: UInt8, 
        /**
         * Absolute path to the raw .osm.pbf extract on device storage.
         */pbfPath: String, 
        /**
         * Absolute path to the DEM GeoTIFF; None skips the Terrain phase.
         */demPath: String?, 
        /**
         * Directory owning this job's checkpoints and output archives.
         */outputDir: String) {
        self.jobId = jobId
        self.bbox = bbox
        self.minZoom = minZoom
        self.maxZoom = maxZoom
        self.pbfPath = pbfPath
        self.demPath = demPath
        self.outputDir = outputDir
    }
}

#if compiler(>=6)
extension CompileJob: Sendable {}
#endif


extension CompileJob: Equatable, Hashable {
    public static func ==(lhs: CompileJob, rhs: CompileJob) -> Bool {
        if lhs.jobId != rhs.jobId {
            return false
        }
        if lhs.bbox != rhs.bbox {
            return false
        }
        if lhs.minZoom != rhs.minZoom {
            return false
        }
        if lhs.maxZoom != rhs.maxZoom {
            return false
        }
        if lhs.pbfPath != rhs.pbfPath {
            return false
        }
        if lhs.demPath != rhs.demPath {
            return false
        }
        if lhs.outputDir != rhs.outputDir {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(jobId)
        hasher.combine(bbox)
        hasher.combine(minZoom)
        hasher.combine(maxZoom)
        hasher.combine(pbfPath)
        hasher.combine(demPath)
        hasher.combine(outputDir)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompileJob: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompileJob {
        return
            try CompileJob(
                jobId: FfiConverterString.read(from: &buf), 
                bbox: FfiConverterString.read(from: &buf), 
                minZoom: FfiConverterUInt8.read(from: &buf), 
                maxZoom: FfiConverterUInt8.read(from: &buf), 
                pbfPath: FfiConverterString.read(from: &buf), 
                demPath: FfiConverterOptionString.read(from: &buf), 
                outputDir: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: CompileJob, into buf: inout [UInt8]) {
        FfiConverterString.write(value.jobId, into: &buf)
        FfiConverterString.write(value.bbox, into: &buf)
        FfiConverterUInt8.write(value.minZoom, into: &buf)
        FfiConverterUInt8.write(value.maxZoom, into: &buf)
        FfiConverterString.write(value.pbfPath, into: &buf)
        FfiConverterOptionString.write(value.demPath, into: &buf)
        FfiConverterString.write(value.outputDir, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompileJob_lift(_ buf: RustBuffer) throws -> CompileJob {
    return try FfiConverterTypeCompileJob.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompileJob_lower(_ value: CompileJob) -> RustBuffer {
    return FfiConverterTypeCompileJob.lower(value)
}


/**
 * Completion report for a finished job.
 */
public struct CompileSummary {
    public var jobId: String
    public var blocksTotal: UInt32
    public var bytesWritten: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(jobId: String, blocksTotal: UInt32, bytesWritten: UInt64) {
        self.jobId = jobId
        self.blocksTotal = blocksTotal
        self.bytesWritten = bytesWritten
    }
}

#if compiler(>=6)
extension CompileSummary: Sendable {}
#endif


extension CompileSummary: Equatable, Hashable {
    public static func ==(lhs: CompileSummary, rhs: CompileSummary) -> Bool {
        if lhs.jobId != rhs.jobId {
            return false
        }
        if lhs.blocksTotal != rhs.blocksTotal {
            return false
        }
        if lhs.bytesWritten != rhs.bytesWritten {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(jobId)
        hasher.combine(blocksTotal)
        hasher.combine(bytesWritten)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompileSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompileSummary {
        return
            try CompileSummary(
                jobId: FfiConverterString.read(from: &buf), 
                blocksTotal: FfiConverterUInt32.read(from: &buf), 
                bytesWritten: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: CompileSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.jobId, into: &buf)
        FfiConverterUInt32.write(value.blocksTotal, into: &buf)
        FfiConverterUInt64.write(value.bytesWritten, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompileSummary_lift(_ buf: RustBuffer) throws -> CompileSummary {
    return try FfiConverterTypeCompileSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompileSummary_lower(_ value: CompileSummary) -> RustBuffer {
    return FfiConverterTypeCompileSummary.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Result of one execution slice.
 *
 * Surface v1 revision (operator-directed hardening pass): the former
 * `Failed` case is split by retryability so the shells can route failures
 * to the right WorkManager/BGTask policy instead of guessing from strings.
 */

public enum CompilationStatus {
    
    /**
     * Compilation for the region is 100% complete; temporary caches purged.
     */
    case finished(summary: CompileSummary
    )
    /**
     * The time budget expired; durable checkpoint written. Re-invoke
     * `compile_chunk` with the same CompileJob to resume.
     */
    case yielded(checkpoint: CheckpointState
    )
    /**
     * A fatal error occurred (corrupted checkpoint, corrupted index, bad
     * input, non-clearing I/O like EACCES). Runners must NOT retry — the
     * same inputs fail the same way.
     */
    case failedFatal(reason: String
    )
    /**
     * The environment refused this slice: another runner holds the job's
     * slice lock, or an I/O operation hit a condition that can clear
     * (ENOSPC — disk full; EIO — transient device error). Durable state
     * is untouched; back off and retry later.
     */
    case failedTransient(reason: String
    )
}


#if compiler(>=6)
extension CompilationStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompilationStatus: FfiConverterRustBuffer {
    typealias SwiftType = CompilationStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompilationStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .finished(summary: try FfiConverterTypeCompileSummary.read(from: &buf)
        )
        
        case 2: return .yielded(checkpoint: try FfiConverterTypeCheckpointState.read(from: &buf)
        )
        
        case 3: return .failedFatal(reason: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .failedTransient(reason: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CompilationStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .finished(summary):
            writeInt(&buf, Int32(1))
            FfiConverterTypeCompileSummary.write(summary, into: &buf)
            
        
        case let .yielded(checkpoint):
            writeInt(&buf, Int32(2))
            FfiConverterTypeCheckpointState.write(checkpoint, into: &buf)
            
        
        case let .failedFatal(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .failedTransient(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompilationStatus_lift(_ buf: RustBuffer) throws -> CompilationStatus {
    return try FfiConverterTypeCompilationStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompilationStatus_lower(_ value: CompilationStatus) -> RustBuffer {
    return FfiConverterTypeCompilationStatus.lower(value)
}


extension CompilationStatus: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Compilation phases, in execution order.
 *
 * P4.C2 surface note: `Pass3Tiles` was appended when the real tile-binning
 * pass landed — a Surface v1 addition made under the operator's Phase-4
 * integration directive (adds a Swift/Kotlin enum case; existing cases and
 * their ordinals are unchanged).
 */

public enum CompilePhase {
    
    case pass1Nodes
    case pass2Ways
    case pass3Tiles
    case terrain
    case finalize
}


#if compiler(>=6)
extension CompilePhase: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompilePhase: FfiConverterRustBuffer {
    typealias SwiftType = CompilePhase

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompilePhase {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .pass1Nodes
        
        case 2: return .pass2Ways
        
        case 3: return .pass3Tiles
        
        case 4: return .terrain
        
        case 5: return .finalize
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CompilePhase, into buf: inout [UInt8]) {
        switch value {
        
        
        case .pass1Nodes:
            writeInt(&buf, Int32(1))
        
        
        case .pass2Ways:
            writeInt(&buf, Int32(2))
        
        
        case .pass3Tiles:
            writeInt(&buf, Int32(3))
        
        
        case .terrain:
            writeInt(&buf, Int32(4))
        
        
        case .finalize:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompilePhase_lift(_ buf: RustBuffer) throws -> CompilePhase {
    return try FfiConverterTypeCompilePhase.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompilePhase_lower(_ value: CompilePhase) -> RustBuffer {
    return FfiConverterTypeCompilePhase.lower(value)
}


extension CompilePhase: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Device thermal pressure, reported by the native shells so the compiler
 * can throttle itself before the OS terminates the process (P8.C1).
 *
 * Suggested platform mapping (the shells own this; Rust never polls):
 * - iOS `ProcessInfo.ThermalState`: `.nominal`/`.fair`/`.serious`/
 * `.critical` map 1:1.
 * - Android `PowerManager` thermal status: `NONE` → Nominal, `LIGHT` →
 * Fair, `MODERATE` → Serious, `SEVERE` and above → Critical.
 *
 * Effect inside the compiler: Nominal/Fair run at full duty cycle (Fair
 * additionally halves parallel-section width); Serious halves the honored
 * slice budget and injects cooling pauses between blocks; Critical makes
 * the very next block boundary checkpoint and return `Yielded`, so the
 * runner can go idle until the OS reports recovery.
 */

public enum ThermalState {
    
    case nominal
    case fair
    case serious
    case critical
}


#if compiler(>=6)
extension ThermalState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeThermalState: FfiConverterRustBuffer {
    typealias SwiftType = ThermalState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ThermalState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .nominal
        
        case 2: return .fair
        
        case 3: return .serious
        
        case 4: return .critical
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ThermalState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .nominal:
            writeInt(&buf, Int32(1))
        
        
        case .fair:
            writeInt(&buf, Int32(2))
        
        
        case .serious:
            writeInt(&buf, Int32(3))
        
        
        case .critical:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThermalState_lift(_ buf: RustBuffer) throws -> ThermalState {
    return try FfiConverterTypeThermalState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThermalState_lower(_ value: ThermalState) -> RustBuffer {
    return FfiConverterTypeThermalState.lower(value)
}


extension ThermalState: Equatable, Hashable {}









/**
 * Progress events emitted from the Rust core to the native (Swift/Kotlin)
 * layer, forwarded to the WebView as Capacitor `compilationProgress` events.
 */
public protocol ProgressCallback: AnyObject, Sendable {
    
    /**
     * `percentage` is 0.0-100.0 across the whole job (not the slice);
     * `status` is a human-readable phase label, e.g.
     * "pass1: indexing nodes (12/62)".
     */
    func onProgress(percentage: Float, status: String) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceProgressCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceProgressCallback] = [UniffiVTableCallbackInterfaceProgressCallback(
        onProgress: { (
            uniffiHandle: UInt64,
            percentage: Float,
            status: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceProgressCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onProgress(
                     percentage: try FfiConverterFloat.lift(percentage),
                     status: try FfiConverterString.lift(status)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceProgressCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface ProgressCallback: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitProgressCallback() {
    uniffi_freehike_ffi_fn_init_callback_vtable_progresscallback(UniffiCallbackInterfaceProgressCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceProgressCallback {
    fileprivate static let handleMap = UniffiHandleMap<ProgressCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceProgressCallback : FfiConverter {
    typealias SwiftType = ProgressCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceProgressCallback_lift(_ handle: UInt64) throws -> ProgressCallback {
    return try FfiConverterCallbackInterfaceProgressCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceProgressCallback_lower(_ v: ProgressCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceProgressCallback.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCheckpointState: FfiConverterRustBuffer {
    typealias SwiftType = CheckpointState?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCheckpointState.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCheckpointState.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
/**
 * Runs one budget-bounded slice of `job`. See module docs for the
 * Finished / Yielded / FailedFatal / FailedTransient contract. Never
 * throws: all failures are values, so foreign call sites need no
 * try/catch ceremony.
 */
public func compileChunk(job: CompileJob, budgetMs: UInt32, callback: ProgressCallback) -> CompilationStatus  {
    return try!  FfiConverterTypeCompilationStatus_lift(try! rustCall() {
    uniffi_freehike_ffi_fn_func_compile_chunk(
        FfiConverterTypeCompileJob_lower(job),
        FfiConverterUInt32.lower(budgetMs),
        FfiConverterCallbackInterfaceProgressCallback_lower(callback),$0
    )
})
}
/**
 * Debug walking-skeleton retained from Phase 1: emits `steps` synthetic
 * progress ticks through the callback and returns how many were sent.
 */
public func emitTestProgress(callback: ProgressCallback, steps: UInt32) -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_freehike_ffi_fn_func_emit_test_progress(
        FfiConverterCallbackInterfaceProgressCallback_lower(callback),
        FfiConverterUInt32.lower(steps),$0
    )
})
}
/**
 * Version string for plugin smoke tests ("is the Rust core actually loaded?").
 */
public func engineVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_freehike_ffi_fn_func_engine_version($0
    )
})
}
/**
 * Cancels a job between slices by deleting its durable state. Returns true
 * if state existed and was removed. (In-slice cancellation is not needed:
 * slices are budget-bounded, so the runner simply stops re-invoking.)
 */
public func purgeJob(jobId: String, outputDir: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_freehike_ffi_fn_func_purge_job(
        FfiConverterString.lower(jobId),
        FfiConverterString.lower(outputDir),$0
    )
})
}
/**
 * Cold-start resume detection: returns the durable checkpoint for a job if
 * one exists (e.g. after the OS killed the process mid-compilation), None
 * if the job has no saved state, or Failed-equivalent None on unreadable
 * state (the next compile_chunk call surfaces the precise error).
 */
public func queryCheckpoint(jobId: String, outputDir: String) -> CheckpointState?  {
    return try!  FfiConverterOptionTypeCheckpointState.lift(try! rustCall() {
    uniffi_freehike_ffi_fn_func_query_checkpoint(
        FfiConverterString.lower(jobId),
        FfiConverterString.lower(outputDir),$0
    )
})
}
/**
 * Publishes the OS-reported thermal level to the compiler core. Callable
 * from ANY foreign thread at any time — including while `compile_chunk`
 * is running on another thread; the write is a single atomic store and
 * running loops pick it up at their next block boundary. The shells
 * should call this from their thermal-notification observers
 * (`thermalStateDidChangeNotification` / `OnThermalStatusChangedListener`)
 * and once at scheduler-window start (notifications don't fire for a
 * state that was already elevated when the process woke).
 */
public func setThermalState(state: ThermalState)  {try! rustCall() {
    uniffi_freehike_ffi_fn_func_set_thermal_state(
        FfiConverterTypeThermalState_lower(state),$0
    )
}
}
/**
 * The thermal level the compiler is currently governed by (Nominal until
 * a shell reports otherwise). For smoke tests and telemetry/UI.
 */
public func thermalState() -> ThermalState  {
    return try!  FfiConverterTypeThermalState_lift(try! rustCall() {
    uniffi_freehike_ffi_fn_func_thermal_state($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_freehike_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_freehike_ffi_checksum_func_compile_chunk() != 59234) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_freehike_ffi_checksum_func_emit_test_progress() != 52095) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_freehike_ffi_checksum_func_engine_version() != 51964) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_freehike_ffi_checksum_func_purge_job() != 63403) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_freehike_ffi_checksum_func_query_checkpoint() != 56823) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_freehike_ffi_checksum_func_set_thermal_state() != 35667) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_freehike_ffi_checksum_func_thermal_state() != 28231) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_freehike_ffi_checksum_method_progresscallback_on_progress() != 34746) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitProgressCallback()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureFreehikeFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all